version: '3.7'

networks:
  jenkins_network:

volumes:
  jenkins_home:

services:
  jenkins:
    container_name: jenkins_app
    build:
      context: docker/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
