pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        always {
            echo "Siempre se ejecuta"
        }
        success{
            echo "Success Pipeline"
        }
        failure{
            echo "Failure Pipeline"
        }
    }

}