pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'cd Jobs/docker'
                sh 'docker-compose build --no-cache'
                sh 'docker-compose up -d
                sh 'docker ps'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        always {
            echo "Siempre se ejecuta"
        }
        success{
            echo "Success Pipeline"
        }
        failure{
            echo "Failure Pipeline"
        }
    }

}